-- ==========================
-- DROP IN DEPENDENCY ORDER
-- ==========================
DROP TABLE IF EXISTS item_editing_table;
DROP TABLE IF EXISTS menu_item_order;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS menu_item_inventory;
DROP TABLE IF EXISTS menu_items;
DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS customers;

DROP TYPE IF EXISTS order_status_enum CASCADE;

-- ==========================
-- ENUM DEFINITIONS
-- ==========================
CREATE TYPE order_status_enum AS ENUM (
    'pending',
    'completed',
    'canceled',
    'in progress',
    'ready to pay',
    'new'
);

-- ==========================
-- TABLE DEFINITIONS
-- ==========================

CREATE TABLE customers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) DEFAULT '' NOT NULL,
    phone VARCHAR(15) NOT NULL UNIQUE,
    payment VARCHAR(50),
    points INT DEFAULT 0 NOT NULL,
    free_drinks INT DEFAULT 0 NOT NULL
);

CREATE TABLE employees (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    permissions INT NOT NULL CHECK (permissions IN (0,1))
);

CREATE TABLE inventory (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    quantity INT NOT NULL
);

CREATE TABLE menu_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    price DECIMAL(8,2) NOT NULL,
    modifications TEXT
);

CREATE TABLE menu_item_inventory (
    menuitemid INT NOT NULL,
    inventoryid INT NOT NULL,
    PRIMARY KEY (menuitemid, inventoryid),
    FOREIGN KEY (menuitemid) REFERENCES menu_items(id) ON DELETE CASCADE,
    FOREIGN KEY (inventoryid) REFERENCES inventory(id) ON DELETE CASCADE
);

CREATE TABLE orders (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status order_status_enum NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    name VARCHAR(255)
);

CREATE TABLE transactions (
    id INT PRIMARY KEY,
    customerid INT NOT NULL,
    employeeid INT NOT NULL,
    total DECIMAL(8,2) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    FOREIGN KEY (id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (customerid) REFERENCES customers(id),
    FOREIGN KEY (employeeid) REFERENCES employees(id)
);

CREATE TABLE menu_item_order (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menuitemid INT NOT NULL,
    orderid INT NOT NULL,
    price_override DECIMAL(8,2), 
    FOREIGN KEY (menuitemid) REFERENCES menu_items(id) ON DELETE CASCADE,
    FOREIGN KEY (orderid) REFERENCES orders(id) ON DELETE CASCADE
);


CREATE TABLE item_editing_table (
    comboid INT PRIMARY KEY,
    sugar VARCHAR(50) NOT NULL,
    ice VARCHAR(50) NOT NULL,
    size VARCHAR(50) NOT NULL,
    shots VARCHAR(50) NOT NULL,
    notes TEXT,
    FOREIGN KEY (comboid) REFERENCES menu_item_order(id) ON DELETE CASCADE
);

-- ==========================
-- IMPORT DATA
-- ==========================
\copy customers              FROM 'customers.csv'           CSV HEADER;
\copy employees              FROM 'employees.csv'           CSV HEADER;
\copy inventory              FROM 'inventory.csv'           CSV HEADER;
\copy menu_items             FROM 'menu_items.csv'          CSV HEADER;
\copy menu_item_inventory    FROM 'menu_item_inventory.csv' CSV HEADER;
\copy orders                 FROM 'orders.csv'              CSV HEADER;
\copy transactions           FROM 'transactions.csv'        CSV HEADER;
\copy menu_item_order (id, menuitemid, orderid) FROM 'menu_item_order.csv' CSV HEADER;
\copy item_editing_table     FROM 'item_editing_table.csv'  CSV HEADER;

-- ==========================
-- INSERT GUEST ACCOUNT (ID = 1)
-- ==========================
INSERT INTO customers (id, name, phone, payment, points, free_drinks)
VALUES (1, 'Guest', '0000000000', NULL, 0, 0)
ON CONFLICT (id) DO NOTHING;

-- ==========================
-- RESET SEQUENCES
-- ==========================
SELECT setval('customers_id_seq',   (SELECT MAX(id) FROM customers) + 1);
SELECT setval('employees_id_seq',   (SELECT MAX(id) FROM employees) + 1);
SELECT setval('inventory_id_seq',   (SELECT MAX(id) FROM inventory) + 1);
SELECT setval('menu_items_id_seq',  (SELECT MAX(id) FROM menu_items) + 1);
SELECT setval('orders_id_seq',      (SELECT MAX(id) FROM orders) + 1);
